EXE    = gi.exe
OFILES = getidmis.o
LIBS   = 
CFLAGS = -g -ansi -pedantic -Wall -Wno-format-overflow -DGOT_PIPES
CC     = x86_64-w64-mingw32-gcc $(CFLAGS)
LFILES = bioplib/StoreString.o

.c.o :
	$(CC) -c -o $@ $<

$(EXE) : $(OFILES) $(LFILES)
	$(CC) -o $(EXE) $(OFILES) $(LFILES)

clean :
	\rm -f $(OFILES) $(LFILES)

distclean : clean
	\rm -f $(EXE)
